Repository sanushshakya/git-session, pull requests merged in 2025-04, with the labels that each got.

#5 Add hmtl file
  sanush.html
Labels: enhancement

#6 Goated
  goated.js
Labels: documentation

#3 printed a text
  test.py
Labels: enhancement

#2 initial commit
  hello.py
Labels: enhancement

#8 added simple html css and js file in fit-dip branch
  index.css
  index.html
  index.js
Labels: documentation

#1 added a new file 'newfile.py'
  newfile.py
Labels: bug

#7 Add calculator webpage
  calculator.html
  file.py
Labels: enhancement

#12 made changes to test.py
  test.py
Labels: bugfix

#13 Fix/prakhar
  hello.py
Labels: bugfix

#18 Revert "Goated"
  goated.js
Labels: bug
